@startuml

object Kunde
Kunde : <size:12>name
Kunde : <size:12>addresse
Kunde : <size:12>telfNummer
Kunde : <size:12>email

object Sælger
Sælger : <size:12>name


object Materialer
Materialer : <size:12>name
Materialer : <size:12>længde
Materialer : <size:12>bredde
Materialer : <size:12>stkPris

object Tilbud
Tilbud : <size:12>stykliste
Tilbud : <size:12>pris
Tilbud : <size:12>kunde
Tilbud : <size:12>dato
Tilbud : <size:12>åben / lukket

object Ordre
Ordre : <size:12>pris
Ordre : <size:12>kunde
Ordre : <size:12>dato

object Carport
Carport : <size:12>type

object Skur
Skur : <size:12>type

object Stykliste
Stykliste : <size:12>carportId
Stykliste : <size:12>styklisteLinjer

object StyklisteLinje
StyklisteLinje : <size:12>beskrivelse
StyklisteLinje : <size:12>materialeName
StyklisteLinje : <size:12>antal
StyklisteLinje : <size:12>pris

Stykliste "1" -- "1" Carport

Stykliste "1" - "*" StyklisteLinje
Materialer "*" - "1" StyklisteLinje

Tilbud "1" -- "1" Ordre
Tilbud "*" -- "1" Kunde

Carport "1" -- "1" Tilbud

Sælger "1" -- "1" Tilbud


Skur . Carport : Optional
@enduml
