@startuml

object Kunde
Kunde : <size:12>name
Kunde : <size:12>addresse
Kunde : <size:12>telfNummer
Kunde : <size:12>email

object Sælger
Sælger : <size:12>name

object Materialer
Materialer : <size:12>name
Materialer : <size:12>længde
Materialer : <size:12>bredde
Materialer : <size:12>stkPris


object Ordre
Ordre : <size:12>pris
Ordre : <size:12>kunde
Ordre : <size:12>tilbusDato
Ordre : <size:12>stykliste
Ordre : <size:12>kunde
Ordre : <size:12>ordreDato
Ordre : <size:12>status


object Carport
Carport : <size:12>længde
Carport : <size:12>bredde
Carport : <size:12>rejsning

object Skur
Skur : <size:12>længde
Skur : <size:12>bredde

object Stykliste
Stykliste : <size:12>carportId
Stykliste : <size:12>styklisteLinjer

object StyklisteLinje
StyklisteLinje : <size:12>beskrivelse
StyklisteLinje : <size:12>materialeName
StyklisteLinje : <size:12>antal
StyklisteLinje : <size:12>pris

Stykliste "1" -- "1" Ordre

Stykliste "1" -- "*" StyklisteLinje
Materialer "*" - "1" StyklisteLinje

Ordre "*" -- "1" Kunde

Carport "1" -- "1" Ordre

Sælger "1" -- "1" Ordre
Skur . Carport : Optional
@enduml
