
Aktivitets Diagram AS-IS
@startuml
skinparam activityFontSize 14
skinparam wrapWidth 160
|Kunde|
start
:Designer carport online;
|Sælger|
:Modtager mail med kundes design;
:Gennemgår design og indtaster specifikationer;

|IT SYSTEM|
:Udregner tilbudspris og genererer stykliste;
|Sælger|
:Sender tilbud til kunden;
|Kunde|
:Kunden modtager tilbud;
|Sælger|
:Kontakter kunden for kompetence vejledning,
evt. specialpris / mersalg;
|Kunde|
if (
<size:14>Kunden accepterer / afslår
)  then (<size:14>accept)
|Sælger|
: Opretter ordre;
|Kunde|
:Kunden betaler, modtager materialer og stykliste;
|Sælger|
:Ordre afsluttes.
Sælger følger op med kunden;
detach
stop
else (<size:14>afslår)
|Sælger|
:tilbud afsluttes;
detach
stop

@enduml

Aktivitets Diagram TO-BE
@startuml
skinparam wrapWidth 160
skinparam activityFontSize 14
|Kunde|
start
:Designer carport online;
|IT SYSTEM|
:Beregner tilbud og udfører stykliste;
|Kunde|
:Modtager autogenereret tilbud;
|Sælger|
:Ser orettet tilbud og stykliste;
:Gennemgår design og autogenereret stykliste;
:Kontakter kunden
evt. specialpris / mersalg;

|Kunde|
:Salgssamtale med sælger;

if (
   <size:14>Accept / Afslår
   ) then (<size:14>accept)
  |Sælger|
  :Opretter ordre;
  stop
else (<size:14>afslår)
|Sælger|
:Redigerer i tilbud;

|IT SYSTEM|
:Beregner nyt tilbud og udfører ny stykliste;
endif
stop
@enduml

|Kunde|
:Kunden betaler, modtager materialer og stykliste;


if (
<size:14>Salgssamtale med sælger
) then (<size:14>accept)
|Sælger|
:Opretter ordre;
|Sælger|
:Ordre afsluttes.
Sælger følger op med kunden;
|Kunde|
:Kunden betaler, modtager materialer og stykl

else (<size:14>afslår)
|Sælger|
:Redigerer i tilbud;
|IT SYSTEM|
:Beregner nyt tilbud og udfører ny stykliste;
endif
