@startuml

object Kunde
Kunde : <size:12>id
Kunde : <size:12>name
Kunde : <size:12>addresse
Kunde : <size:12>telfNummer
Kunde : <size:12>email

object Sælger
Sælger : <size:12>id
Sælger : <size:12>name


object Materialer
Materialer : <size:12>name
Materialer : <size:12>længde
Materialer : <size:12>bredde
Materialer : <size:12>stkPris

object Tilbud
Tilbud : <size:12>id
Tilbud : <size:12>materialer
Tilbud : <size:12>pris
Tilbud : <size:12>kunde
Tilbud : <size:12>dato
Tilbud : <size:12>åben

object Ordre
Ordre : <size:12>id
Ordre : <size:12>pris
Ordre : <size:12>kunde
Ordre : <size:12>dato

object Carport
Carport : <size:12>id
Carport : <size:12>type

object Skur
Skur : <size:12>id
Skur : <size:12>type

object Stykliste
Stykliste : <size:12>id
Stykliste : <size:12>carportId


Materialer "*" o-- "1" Ordre
Materialer "*" o-- "1" Tilbud
Tilbud "*" o-- "1" Kunde
Ordre"*" o-- "1" Kunde
Materialer "*" o-- "1" Tilbud
Stykliste "1" -- "1" Tilbud
Carport "1" -- "1" Tilbud
Carport "1" -- "1" Ordre
Sælger "1" -- "1" Tilbud
Sælger "1" -- "1" Ordre


Skur . Carport : Optional
@enduml
