
Aktivitets Diagram AS-IS
@startuml
skinparam activityFontSize 14
skinparam wrapWidth 160
|Kunde|
start
:Designer carport
online;
|Sælger|
:Modtager mail med kundes design;
:Gennemgår design og autogenereret stykliste.

Udregner tilbudspris på baggrund af stykliste
og autogenereret stykliste;
:Sender tilbud til kunden;
|Kunde|
:Kunden modtager tilbud;
|Sælger|
:Kontakter kunden for kompetence vejledning,
evt. specialpris / mersalg;
|Kunde|
:Kunden accepterer / afslår;
|Sælger|

if (
<size:14>Opretter ordre
)
|Ledelse|
:Kan følge salgsmål og lønsomhed;
detach
else
|Kunde|
:Kunden betaler, modtager materialer og stykliste;
|Sælger|
:Ordre afsluttes.
Sælger følger op med kunden.;
stop


@enduml

Aktivitets Diagram TO-BE
@startuml
skinparam wrapWidth 110
skinparam activityFontSize 14
|Kunde|
start
:Designer carport online;
:Modtager autogenereret tilbud;
|Sælger|
:Ser orettet tilbud og stykliste;
:Gennemgår design og autogenereret stykliste;
:Kontakter kunden;
|Kunde|

if (
<size:14>Salgssamtale
<size:14>med sælger
)
|Sælger|
:Redigerer i tilbud
evt. specialpris / mersalg;
detach
else
|Kunde|
:Kunden accepterer / afslår;
|Sælger|
if (
<size:14>Opretter ordre
)
|Ledelse|
:Kan følge salgsmål og lønsomhed;
detach
else
|Kunde|
:Kunden betaler, modtager materialer og stykliste;
|Sælger|
:Ordre afsluttes.
Sælger følger op med kunden.;
stop


@enduml

